title: Mathias Getaneh
logo: images/SmallProfilePicture.jpg
description: Graduate Student and aspiring Data Scientist.
#<br><br>
#<a href="linkedin.com/in/mathias-getaneh-3078072a2">View My LinkedIn Profile</a>
#show_downloads: true
theme: jekyll-theme-minimal
